"""Firmas de los `MaterialExpression` de Unreal. GENERADO — no editar a mano.

Lo produce `tools/experiments/volcar_firmas.py` corriendo dentro del editor, que es el único lado
que puede preguntarle al motor cómo se llaman las entradas de cada nodo. Se commitea para que el
verificador de `jam.shader` funcione en Python pelado, sin Unreal, y `verifica_material_verbos.py`
comprueba que no se haya quedado vieja.

Dos cosas que se leen mal si uno no las espera:

* los nodos de UNA sola entrada la llaman ``"None"`` — no es que no tengan entrada;
* hay tipos sin ninguna entrada (constantes, parámetros, coordenadas): tupla vacía.

Motor: 5.7.4  ·  408 tipos.
"""

from __future__ import annotations

ENTRADAS: dict[str, tuple[str, ...]] = {
    'Abs': ('None',),
    'AbsorptionMediumMaterialOutput': ('TransmittanceColor',),
    'ActorPositionWS': (),
    'Add': ('A', 'B'),
    'Aggregate': ('MaterialAttributes',),
    'AntialiasedTextureMask': ('UVs', 'Apply View MipBias'),
    'Append3Vector': ('A', 'B', 'C'),
    'Append4Vector': ('A', 'B', 'C', 'D'),
    'AppendVector': ('A', 'B'),
    'Arccosine': ('None',),
    'ArccosineFast': ('None',),
    'Arcsine': ('None',),
    'ArcsineFast': ('None',),
    'Arctangent': ('None',),
    'Arctangent2': ('Y', 'X'),
    'Arctangent2Fast': ('Y', 'X'),
    'ArctangentFast': ('None',),
    'AtmosphericFogColor': ('World Position',),
    'AtmosphericLightColor': (),
    'AtmosphericLightVector': (),
    'BentNormalCustomOutput': ('None',),
    'BindlessSwitch': ('Default', 'Bindless'),
    'BlackBody': ('Temp',),
    'Blend': ('A', 'B', 'Alpha'),
    'BlendMaterialAttributes': ('A', 'B', 'Alpha'),
    'Bounds': (),
    'BreakMaterialAttributes': ('Attr',),
    'BumpOffset': ('Coordinate', 'Height', 'HeightRatioInput'),
    'Burn': ('A', 'B', 'Alpha'),
    'CameraPositionWS': (),
    'CameraVectorWS': (),
    'Ceil': ('None',),
    'ChannelMaskParameter': ('None',),
    'Clamp': ('None', 'Min', 'Max'),
    'ClearCoatNormalCustomOutput': ('None',),
    'CloudSampleAttribute': (),
    'CollectionParameter': (),
    'CollectionTransform': ('None',),
    'ColorRamp': ('None',),
    'Comment': (),
    'ComponentMask': ('None',),
    'Composite': (),
    'Constant': (),
    'Constant2Vector': (),
    'Constant3Vector': (),
    'Constant4Vector': (),
    'ConstantBiasScale': ('None',),
    'ConstantDouble': (),
    'Convert': (),
    'Cosine': ('None',),
    'CrossProduct': ('A', 'B'),
    'CurveAtlasRowParameter': ('CurveTime',),
    'Custom': ('None',),
    'CustomOutput': (),
    'DBufferTexture': ('UVs',),
    'DDX': ('Value',),
    'DDY': ('Value',),
    'DataDrivenShaderPlatformInfoSwitch': ('None', '!()'),
    'DecalColor': (),
    'DecalDerivative': (),
    'DecalLifetimeOpacity': (),
    'DecalMipmapLevel': ('TextureSize',),
    'DeltaTime': (),
    'DepthFade': ('Opacity', 'FadeDistance'),
    'DepthOfFieldFunction': ('Depth',),
    'DeriveNormalZ': ('InXY',),
    'Desaturation': ('None', 'Fraction'),
    'Difference': ('A', 'B', 'Alpha'),
    'DisjointOver': ('A', 'B', 'Alpha'),
    'Distance': ('A', 'B'),
    'DistanceCullFade': (),
    'DistanceFieldApproxAO': ('World Position', 'Normal', 'BaseDistance', 'Radius'),
    'DistanceFieldGradient': ('World Position',),
    'DistanceFieldsRenderingSwitch': ('No', 'Yes'),
    'DistanceToNearestSurface': ('World Position',),
    'Divide': ('A', 'B'),
    'Dodge': ('A', 'B', 'Alpha'),
    'DotProduct': ('A', 'B'),
    'DoubleVectorParameter': (),
    'DynamicParameter': (),
    'Exponential': ('None',),
    'Exponential2': ('None',),
    'ExternalCodeBase': (),
    'EyeAdaptation': (),
    'EyeAdaptationInverse': ('LightValueInput', 'AlphaInput'),
    'FeatureLevelSwitch': ('Default', 'ES2', 'ES3_1', 'SM4_REMOVED', 'SM5', 'SM6'),
    'FirstPersonOutput': ('FirstPersonInterpolationAlpha',),
    'FloatToUInt': ('None',),
    'Floor': ('None',),
    'Fmod': ('A', 'B'),
    'FontSample': (),
    'FontSampleParameter': (),
    'FontSignedDistance': (),
    'Frac': ('None',),
    'Fractal3D': ('Position', 'Amplitude', 'Octaves', 'Lacunarity', 'Diminish'),
    'Fresnel': ('ExponentIn', 'BaseReflectFractionIn', 'Normal'),
    'FunctionInput': ('Preview',),
    'FunctionOutput': ('None',),
    'GIReplace': ('Default', 'StaticIndirect', 'DynamicIndirect'),
    'GenericConstant': (),
    'GetMaterialAttributes': ('None',),
    'HairAttributes': (),
    'HairColor': ('Melanin', 'Redness', 'DyeColor'),
    'HsvToRgb': ('None',),
    'If': ('A', 'B', 'A > B', 'A == B', 'A < B'),
    'IfThenElse': ('Condition', 'True', 'False'),
    'In': ('A', 'B', 'Alpha'),
    'InverseLinearInterpolate': ('A', 'B', 'Value'),
    'IsFirstPerson': (),
    'IsOrthographic': (),
    'LandscapeGrassOutput': ('Grass',),
    'LandscapeLayerBlend': (),
    'LandscapeLayerCoords': (),
    'LandscapeLayerSample': (),
    'LandscapeLayerSwitch': ('LayerUsed', 'LayerNotUsed'),
    'LandscapeLayerWeight': ('Base', 'Layer'),
    'LandscapePhysicalMaterialOutput': (),
    'LandscapeVisibilityMask': (),
    'LayerStack': (),
    'LegacyBlendMaterialAttributes': ('A', 'B', 'Alpha'),
    'Length': ('None',),
    'LightVector': (),
    'LightmapUVs': (),
    'LightmassReplace': ('Realtime', 'Lightmass'),
    'LinearInterpolate': ('A', 'B', 'Alpha'),
    'LocalPosition': (),
    'Logarithm': ('None',),
    'Logarithm10': ('X',),
    'Logarithm2': ('X',),
    'Luminance': ('None',),
    'MakeMaterialAttributes': ('BaseColor', 'Metallic', 'Specular', 'Roughness', 'Anisotropy', 'EmissiveColor', 'Opacity', 'OpacityMask', 'Normal', 'Tangent', 'WorldPositionOffset', 'SubsurfaceColor', 'ClearCoat', 'ClearCoatRoughness', 'AmbientOcclusion', 'Refraction', 'CustomizedUVs_0', 'CustomizedUVs_1', 'CustomizedUVs_2', 'CustomizedUVs_3', 'CustomizedUVs_4', 'CustomizedUVs_5', 'CustomizedUVs_6', 'CustomizedUVs_7', 'PixelDepthOffset', 'ShadingModel', 'Displacement'),
    'MapARPassthroughCameraUV': ('UVs',),
    'Mask': ('A', 'B', 'Alpha'),
    'MaterialAttributeLayers': ('None',),
    'MaterialCache': ('BaseColor', 'Roughness', 'Normal', 'Specular', 'Opacity', 'Metallic'),
    'MaterialFunctionCall': (),
    'MaterialLayerOutput': ('None',),
    'MaterialProxyReplace': ('Realtime', 'MaterialProxy'),
    'MaterialSample': (),
    'MaterialXAppend3Vector': ('A', 'B', 'C'),
    'MaterialXAppend4Vector': ('A', 'B', 'C', 'D'),
    'MaterialXBurn': ('A', 'B', 'Alpha'),
    'MaterialXContrast': ('None', 'Amount', 'Pivot'),
    'MaterialXDifference': ('A', 'B', 'Alpha'),
    'MaterialXDisjointOver': ('A', 'B', 'Alpha'),
    'MaterialXDodge': ('A', 'B', 'Alpha'),
    'MaterialXExponential': ('None',),
    'MaterialXFractal3D': ('Position', 'Amplitude', 'Octaves', 'Lacunarity', 'Diminish'),
    'MaterialXHsvToRgb': ('None',),
    'MaterialXIn': ('A', 'B', 'Alpha'),
    'MaterialXLength': ('None',),
    'MaterialXLogarithm': ('None',),
    'MaterialXLuminance': ('None',),
    'MaterialXMask': ('A', 'B', 'Alpha'),
    'MaterialXMatte': ('A', 'B', 'Alpha'),
    'MaterialXMinus': ('A', 'B', 'Alpha'),
    'MaterialXMod': ('A', 'B'),
    'MaterialXOut': ('A', 'B', 'Alpha'),
    'MaterialXOver': ('A', 'B', 'Alpha'),
    'MaterialXOverlay': ('A', 'B', 'Alpha'),
    'MaterialXPlace2D': ('UVs', 'Pivot', 'Scale', 'Offset', 'RotationAngle'),
    'MaterialXPlus': ('A', 'B', 'Alpha'),
    'MaterialXPremult': ('None',),
    'MaterialXRamp4': ('UVs', 'A', 'B', 'C', 'D'),
    'MaterialXRampLeftRight': ('UVs', 'A', 'B'),
    'MaterialXRampTopBottom': ('UVs', 'A', 'B'),
    'MaterialXRange': ('None', 'InputLow', 'InputHigh', 'TargetLow', 'TargetHigh', 'Gamma', 'Clamp'),
    'MaterialXRemap': ('None', 'InputLow', 'InputHigh', 'TargetLow', 'TargetHigh'),
    'MaterialXRgbToHsv': ('None',),
    'MaterialXRotate2D': ('None', 'RotationAngle'),
    'MaterialXScreen': ('A', 'B', 'Alpha'),
    'MaterialXSplitLeftRight': ('UVs', 'A', 'B', 'Center'),
    'MaterialXSplitTopBottom': ('UVs', 'A', 'B', 'Center'),
    'MaterialXSwizzle': ('None',),
    'MaterialXTextureSampleParameterBlur': ('UVs', 'Apply View MipBias'),
    'MaterialXUnpremult': ('None',),
    'Matte': ('A', 'B', 'Alpha'),
    'Max': ('A', 'B'),
    'MeshPaintTextureCoordinateIndex': (),
    'MeshPaintTextureObject': (),
    'MeshPaintTextureReplace': ('Default', 'MeshPaintTexture'),
    'Min': ('A', 'B'),
    'Minus': ('A', 'B', 'Alpha'),
    'Modulo': ('A', 'B'),
    'MotionVectorWorldOffsetOutput': ('None',),
    'Multiply': ('A', 'B'),
    'NamedRerouteBase': (),
    'NamedRerouteDeclaration': ('None',),
    'NamedRerouteUsage': (),
    'NaniteReplace': ('Default', 'Nanite'),
    'NeuralNetworkInput': ('UVs', 'Input0', 'Mask'),
    'NeuralNetworkOutput': ('UVs',),
    'Noise': ('World Position', 'FilterWidth'),
    'Normalize': ('VectorInput',),
    'ObjectBounds': (),
    'ObjectLocalBounds': (),
    'ObjectOrientation': (),
    'ObjectPositionWS': (),
    'ObjectRadius': (),
    'OneMinus': ('None',),
    'Operator': ('A', 'B'),
    'Out': ('A', 'B', 'Alpha'),
    'Over': ('A', 'B', 'Alpha'),
    'Overlay': ('A', 'B', 'Alpha'),
    'Panner': ('Coordinate', 'Time', 'Speed'),
    'Parameter': (),
    'ParticleColor': (),
    'ParticleDirection': (),
    'ParticleMacroUV': (),
    'ParticleMotionBlurFade': (),
    'ParticlePositionWS': (),
    'ParticleRadius': (),
    'ParticleRandom': (),
    'ParticleRelativeTime': (),
    'ParticleSize': (),
    'ParticleSpeed': (),
    'ParticleSpriteRotation': (),
    'ParticleSubUV': ('UVs', 'Tex', 'Apply View MipBias'),
    'ParticleSubUVProperties': (),
    'PathTracingBufferTexture': ('UVs',),
    'PathTracingQualitySwitch': ('Normal', 'PathTraced'),
    'PathTracingRayTypeSwitch': ('Main', 'Shadow', 'IndirectDiffuse', 'IndirectSpecular', 'IndirectVolume'),
    'PerInstanceCustomData': ('DefaultValue',),
    'PerInstanceCustomData3Vector': ('DefaultValue',),
    'PerInstanceFadeAmount': (),
    'PerInstanceRandom': (),
    'PinBase': (),
    'PixelDepth': (),
    'PixelNormalWS': (),
    'Place2D': ('UVs', 'Pivot', 'Scale', 'Offset', 'RotationAngle'),
    'Plus': ('A', 'B', 'Alpha'),
    'PostVolumeUserFlagTest': ('BitIndex',),
    'Power': ('Base', 'Exp'),
    'PreSkinnedLocalBounds': (),
    'PreSkinnedNormal': (),
    'PreSkinnedPosition': (),
    'PrecomputedAOMask': (),
    'Premult': ('None',),
    'PreviousFrameSwitch': ('Current Frame', 'Previous Frame'),
    'QualitySwitch': ('Default', 'Low', 'High', 'Medium', 'Epic'),
    'Ramp4': ('UVs', 'A', 'B', 'C', 'D'),
    'RampLeftRight': ('UVs', 'A', 'B'),
    'RampTopBottom': ('UVs', 'A', 'B'),
    'RayTracingQualitySwitch': ('Normal', 'RayTraced'),
    'RecordTextureStreamingInfo': ('Tex', 'UVs'),
    'ReflectionCapturePassSwitch': ('Default', 'Reflection'),
    'ReflectionVectorWS': ('CustomWorldNormal',),
    'Remap': ('None', 'InputLow', 'InputHigh', 'TargetLow', 'TargetHigh'),
    'RequiredSamplersSwitch': ('Within platform limit', 'Over platform limit'),
    'Reroute': ('None',),
    'RerouteBase': (),
    'RgbToHsv': ('None',),
    'Rotate2D': ('None', 'RotationAngle'),
    'RotateAboutAxis': ('NormalizedRotationAxis', 'RotationAngle', 'PivotPoint', 'Position'),
    'Rotator': ('Coordinate', 'Time'),
    'Round': ('None',),
    'RuntimeVirtualTextureCustomData': (),
    'RuntimeVirtualTextureOutput': ('BaseColor', 'Specular', 'Roughness', 'Normal', 'WorldHeight', 'Opacity', 'Mask', 'Displacement', 'Mask4'),
    'RuntimeVirtualTextureReplace': ('Default', 'VirtualTextureOutput'),
    'RuntimeVirtualTextureSample': ('UVs', 'World Position'),
    'RuntimeVirtualTextureSampleParameter': ('UVs', 'World Position'),
    'SRGBColorToWorkingColorSpace': ('None',),
    'SamplePhysicsIntegerField': ('World Position',),
    'SamplePhysicsScalarField': ('World Position',),
    'SamplePhysicsVectorField': ('World Position',),
    'Saturate': ('None',),
    'ScalarBlueNoise': (),
    'ScalarParameter': (),
    'SceneColor': ('UVs',),
    'SceneDepth': ('UVs',),
    'SceneDepthWithoutWater': ('UVs',),
    'SceneTexelSize': (),
    'SceneTexture': ('UVs',),
    'Screen': ('A', 'B', 'Alpha'),
    'ScreenPosition': (),
    'SetMaterialAttributes': ('MaterialAttributes',),
    'ShaderStageSwitch': ('PixelShader', 'VertexShader'),
    'ShadingModel': (),
    'ShadingPathSwitch': ('Default', 'Deferred', 'Forward', 'Mobile'),
    'ShadowReplace': ('Default', 'Shadow'),
    'Sign': ('None',),
    'Sine': ('None',),
    'SingleLayerWaterMaterialOutput': ('ScatteringCoefficients', 'AbsorptionCoefficients', 'PhaseG', 'ColorScaleBehindWater'),
    'SkyAtmosphereAerialPerspective': ('World Position',),
    'SkyAtmosphereDistantLightScatteredLuminance': (),
    'SkyAtmosphereLightDirection': (),
    'SkyAtmosphereLightDiskLuminance': ('DiskAngularDiameterOverride',),
    'SkyAtmosphereLightIlluminance': ('World Position',),
    'SkyAtmosphereLightIlluminanceOnGround': (),
    'SkyAtmosphereViewLuminance': ('WorldDirection',),
    'SkyLightEnvMapSample': ('Direction', 'Roughness'),
    'SmoothStep': ('Min', 'Max', 'Value'),
    'Sobol': ('Cell', 'Index', 'Seed'),
    'SparseVolumeTextureBase': (),
    'SparseVolumeTextureObject': (),
    'SparseVolumeTextureObjectParameter': ('UVs', 'Tex'),
    'SparseVolumeTextureSample': ('UVs', 'Tex'),
    'SparseVolumeTextureSampleParameter': ('UVs', 'Tex'),
    'SpeedTree': ('GeometryInput', 'WindInput', 'LODInput', 'ExtraBendWS'),
    'SphereMask': ('A', 'B', 'Radius', 'Hardness'),
    'SphericalParticleOpacity': ('Density',),
    'SplitLeftRight': ('UVs', 'A', 'B', 'Center'),
    'SplitTopBottom': ('UVs', 'A', 'B', 'Center'),
    'SpriteTextureSampler': ('UVs', 'Apply View MipBias'),
    'SquareRoot': ('None',),
    'StaticBool': (),
    'StaticBoolParameter': (),
    'StaticComponentMaskParameter': ('None',),
    'StaticSwitch': ('True', 'False', 'Value'),
    'StaticSwitchParameter': ('True', 'False'),
    'Step': ('Y', 'X'),
    'StrataAdd': ('A', 'B'),
    'StrataBSDF': (),
    'StrataConvertToDecal': ('DecalMaterial', 'Coverage'),
    'StrataEyeBSDF': ('DiffuseColor', 'Roughness', 'CorneaNormal', 'IrisNormal', 'IrisPlaneNormal', 'IrisMask', 'IrisDistance', 'EmissiveColor'),
    'StrataHairBSDF': ('BaseColor', 'Scatter', 'Specular', 'Roughness', 'Backlit', 'Tangent', 'EmissiveColor'),
    'StrataHazinessToSecondaryRoughness': ('BaseRoughness', 'Haziness'),
    'StrataHorizontalMixing': ('Background', 'Foreground', 'Mix'),
    'StrataLegacyConversion': ('BaseColor', 'Metallic', 'Specular', 'Roughness', 'Anisotropy', 'Emissive Color', 'Normal', 'Tangent', 'Subsurface Color', 'Unused', 'Unused', 'Opacity', 'Thin Translucent Transmittance Color', 'Water Scattering Coefficients', 'Water Absorption Coefficients', 'Water Phase G', 'Color Scale BehindWater', 'Unused', 'Custom Tangent', 'Thin Translucent Surface Coverage', 'Single Shading Model'),
    'StrataLightFunction': ('Color',),
    'StrataMetalnessToDiffuseAlbedoF0': ('BaseColor', 'Metallic', 'Specular'),
    'StrataPostProcess': ('Color', 'Opacity'),
    'StrataSimpleClearCoatBSDF': ('Diffuse Albedo', 'F0', 'Roughness', 'Clear Coat Coverage', 'Clear Coat Roughness', 'Normal', 'Emissive Color', 'Bottom Normal'),
    'StrataSingleLayerWaterBSDF': ('BaseColor', 'Metallic', 'Specular', 'Roughness', 'Normal', 'EmissiveColor', 'TopMaterialOpacity', 'WaterAlbedo', 'WaterExtinction', 'WaterPhaseG', 'ColorScaleBehindWater'),
    'StrataSlabBSDF': ('Diffuse Albedo', 'F0', 'F90', 'Roughness', 'Anisotropy', 'Normal', 'Tangent', 'SSS MFP', 'SSS MFP Scale', 'SSS Phase Anisotropy', 'Emissive Color', 'Second Roughness', 'Second Roughness Weight', 'Fuzz Roughness', 'Fuzz Amount', 'Fuzz Color', 'Glint Density (Disabled)', 'Glint UVs (Disabled)'),
    'StrataThinFilm': ('Normal', 'F0', 'F90', 'Thickness', 'IOR'),
    'StrataTransmittanceToMFP': ('TransmittanceColor', 'Thickness'),
    'StrataUI': ('Color', 'Opacity'),
    'StrataUnlitBSDF': ('EmissiveColor', 'TransmittanceColor', 'Normal'),
    'StrataUtilityBase': (),
    'StrataVerticalLayering': ('Top', 'Bottom', 'Top Thickness'),
    'StrataVolumetricFogCloudBSDF': ('Albedo', 'Extinction', 'EmissiveColor', 'AmbientOcclusion'),
    'StrataWeight': ('A', 'Weight'),
    'SubstrateAdd': ('A', 'B'),
    'SubstrateBSDF': (),
    'SubstrateConvertMaterialAttributes': ('Attributes', 'Water Scattering Coefficients (Water)', 'Water Absorption Coefficients (Water)', 'Water Phase G (Water)', 'Color Scale BehindWater (Water)'),
    'SubstrateConvertToDecal': ('DecalMaterial', 'Coverage'),
    'SubstrateEyeBSDF': ('DiffuseColor', 'Roughness', 'CorneaNormal', 'IrisNormal', 'IrisPlaneNormal', 'IrisMask', 'IrisDistance', 'EmissiveColor'),
    'SubstrateHairBSDF': ('BaseColor', 'Scatter', 'Specular', 'Roughness', 'Backlit', 'Tangent', 'EmissiveColor'),
    'SubstrateHazinessToSecondaryRoughness': ('BaseRoughness', 'Haziness'),
    'SubstrateHorizontalMixing': ('Background', 'Foreground', 'Mix'),
    'SubstrateLightFunction': ('Color',),
    'SubstrateMetalnessToDiffuseAlbedoF0': ('BaseColor', 'Metallic', 'Specular'),
    'SubstratePostProcess': ('Color', 'Opacity'),
    'SubstrateSelect': ('A', 'B', 'SelectValue'),
    'SubstrateShadingModels': ('BaseColor', 'Metallic', 'Specular', 'Roughness', 'Anisotropy', 'Emissive Color', 'Normal', 'Tangent', 'Subsurface Color', 'Unused', 'Unused', 'Opacity', 'Thin Translucent Transmittance Color', 'Water Scattering Coefficients', 'Water Absorption Coefficients', 'Water Phase G', 'Color Scale BehindWater', 'Unused', 'Custom Tangent', 'Thin Translucent Surface Coverage', 'Single Shading Model'),
    'SubstrateSimpleClearCoatBSDF': ('Diffuse Albedo', 'F0', 'Roughness', 'Clear Coat Coverage', 'Clear Coat Roughness', 'Normal', 'Emissive Color', 'Bottom Normal'),
    'SubstrateSingleLayerWaterBSDF': ('BaseColor', 'Metallic', 'Specular', 'Roughness', 'Normal', 'EmissiveColor', 'TopMaterialOpacity', 'WaterAlbedo', 'WaterExtinction', 'WaterPhaseG', 'ColorScaleBehindWater'),
    'SubstrateSlabBSDF': ('Diffuse Albedo', 'F0', 'F90', 'Roughness', 'Anisotropy', 'Normal', 'Tangent', 'SSS MFP', 'SSS MFP Scale', 'SSS Phase Anisotropy', 'Emissive Color', 'Second Roughness', 'Second Roughness Weight', 'Fuzz Roughness', 'Fuzz Amount', 'Fuzz Color', 'Glint Density (Disabled)', 'Glint UVs (Disabled)'),
    'SubstrateThinFilm': ('Normal', 'F0', 'F90', 'Thickness', 'IOR'),
    'SubstrateTransmittanceToMFP': ('TransmittanceColor', 'Thickness'),
    'SubstrateUI': ('Color', 'Opacity'),
    'SubstrateUnlitBSDF': ('EmissiveColor', 'TransmittanceColor', 'Normal'),
    'SubstrateUtilityBase': (),
    'SubstrateVerticalLayering': ('Top', 'Bottom', 'Top Thickness'),
    'SubstrateVolumetricFogCloudBSDF': ('Albedo', 'Extinction', 'EmissiveColor', 'AmbientOcclusion'),
    'SubstrateWeight': ('A', 'Weight'),
    'SubsurfaceMediumMaterialOutput': ('MeanFreePath', 'ScatteringDistribution'),
    'Subtract': ('A', 'B'),
    'Switch': ('SwitchValue', 'Default', 'None'),
    'Tangent': ('None',),
    'TangentOutput': ('None',),
    'TemporalResponsivenessOutput': ('None',),
    'TemporalSobol': ('Index', 'Seed'),
    'TerrainLayerCoords': (),
    'TerrainLayerSwitch': ('LayerUsed', 'LayerNotUsed'),
    'TerrainLayerWeight': ('Base', 'Layer'),
    'TextureBase': (),
    'TextureCollection': (),
    'TextureCollectionParameter': (),
    'TextureCoordinate': (),
    'TextureObject': (),
    'TextureObjectFromCollection': ('TextureCollection', 'CollectionIndex'),
    'TextureObjectParameter': ('UVs', 'Apply View MipBias'),
    'TextureProperty': ('Tex',),
    'TextureSample': ('UVs', 'Tex', 'Apply View MipBias'),
    'TextureSampleParameter': ('UVs', 'Apply View MipBias'),
    'TextureSampleParameter2D': ('UVs', 'Apply View MipBias'),
    'TextureSampleParameter2DArray': ('UVs', 'Apply View MipBias'),
    'TextureSampleParameterBlur': ('UVs', 'Apply View MipBias'),
    'TextureSampleParameterCube': ('UVs', 'Apply View MipBias'),
    'TextureSampleParameterCubeArray': ('UVs', 'Apply View MipBias'),
    'TextureSampleParameterSubUV': ('UVs', 'Apply View MipBias'),
    'TextureSampleParameterVolume': ('UVs', 'Apply View MipBias'),
    'ThinTranslucentMaterialOutput': ('TransmittanceColor', 'SurfaceCoverage'),
    'Time': (),
    'Transform': ('None',),
    'TransformPosition': ('None',),
    'Truncate': ('None',),
    'TruncateLWC': ('None',),
    'TwoSidedSign': (),
    'UIntToFloat': ('None',),
    'Unpremult': ('None',),
    'UserSceneTexture': ('UVs',),
    'VectorNoise': ('World Position',),
    'VectorParameter': (),
    'VertexColor': (),
    'VertexInterpolator': ('VS',),
    'VertexNormalWS': (),
    'VertexTangentWS': (),
    'ViewProperty': (),
    'ViewSize': (),
    'VirtualTextureFeatureSwitch': ('No', 'Yes'),
    'VolumetricAdvancedMaterialInput': (),
    'VolumetricAdvancedMaterialOutput': ('PhaseG', 'PhaseG2', 'PhaseBlend', 'MultiScatteringContribution', 'MultiScatteringOcclusion', 'MultiScatteringEccentricity', 'ConservativeDensity'),
    'VolumetricCloudEmptySpaceSkippingInput': (),
    'VolumetricCloudEmptySpaceSkippingOutput': ('ContainsMatter',),
    'WorldPosition': (),
}
